name: ipcc_test
channels:
  - defaults
dependencies:
  - python=3.7.0
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pip=20.3
  - requests=2.25.1
  - scipy=1.5.2
  - cartopy=0.18.0
  - pandas=1.1.5
  - xarray=0.16.2
  - dask=2020.12.0
  - netcdf4=1.4.1
- pip:
    - projmap==0.87
